- name: Install MySQL
  hosts: mysql
  become: yes

  tasks:
  - name: disable current version of mysql
    ansible.builtin.command: dnf module disable mysql -y
    #CentOS-8 Comes with MySQL 8 Version by default, However our application needs MySQL 5.7. So lets disable MySQL 8 version.

  - name: Setup MySQL 5.7 Repo
    ansible.builtin.copy: 
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install MySQL Server
    ansible.builtin.package:
      name: mysql-community-server
      state: present

  - name: Start and Enable Mysql # Befoer setup we need to start
    ansible.builtin.service:
      name: mysqld
      state: started #restarted is also fine
      enabled: yes

  - name: Setup a ROOT Password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

  # mysql -uroot -pRoboShop@1 -->You can check the new password working or not using the following command in MySQL.


